# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Image-slider' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Image-slider
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SDWebImage', '4.4.6'

end
